### ISSUE TITLE
Cannot translate "string.SubString(string.IndexOf(char)+1)"

### ISSUE THREAD

**Issue by Flithor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1713]
### Steps to reproduce
Code below: (works in LINQPad)

`MyEntity1.Where(e1=>!MyEntity2.Select(e2 => e2.Prop2.Substring(e2.Prop2.IndexOf('_')+1)).Contains(e1.Prop1)).ToList();`

That's means "found the items in table MyEntity1 where the property Prop1 not match anyone the substring of property Prop2 after first '_' char in table MyEntity2"

I've found the code: `MyEntity2.Select(e2 => e2.Prop2.Substring(e2.Prop2.IndexOf('_') + 1)).ToList()` translate to sql is:
```SQL
SELECT `m`.`Prop2` FROM `MyEntity2` AS `m`
```
But the expectation should be:
```SQL
SELECT SUBSTR(`Prop2`,LOCATE('_',`Prop2`)+1) FROM `MyEntity2`
```

### The issue
```
Exception message:
InvalidOperationException: The LINQ expression 'DbSet<MyEntity2>()
    .Select(e2 => e2.Prop2.Substring(e2.Prop2.IndexOf(_) + 1))
    .Any(e1 => e1 == EntityShaperExpression: 
        EntityType: MyEntity2
        ValueBufferExpression: 
            ProjectionBindingExpression: EmptyProjectionMember
        IsNullable: False
    .Prop1)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Further technical details

MySQL version: 8.0.29
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: NONE

Other details about my project setup: Nothing

BTW try fix this:

`MyEntity1.Where(e1=>!MyEntity2.Any(e2 => e2.Prop2.Substring(e2.Prop2.IndexOf('_')+1) == e1.Prop1)).ToList();`

```
InvalidOperationException: The LINQ expression 'DbSet<MyEntity2>()
    .Any(e2 => e2.Prop2.Substring(e2.Prop2.IndexOf(_) + 1) == EntityShaperExpression: 
        EntityType: MyEntity1
        ValueBufferExpression: 
            ProjectionBindingExpression: EmptyProjectionMember
        IsNullable: False
    .Prop1)' could not be translated. Additional information: Translation of method 'string.IndexOf' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
 ```
